[package]
name = "scylla-migration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
clap = { version = "4.3.11", features = ["derive"] }
scylla = "0.8.2"
serde = { version = "1.0.171", features = ["derive"] }
serde_yaml = "0.9.22"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
